### ISSUE TITLE
OSError: [Errno 20] Not a directory: '/home/liuxg/.dict_youdao/stardict/21shijishuangxiangcidian.dict'

### ISSUE THREAD

**Issue by liu-xiao-guo** [longcw/youdao#8]
按照步骤，我把文件拷入到路径：
liuxg@liuxg:~/.dict_youdao/stardict$ ls
21shijishuangxiangcidian.dict  21shijishuangxiangcidian.idx  21shijishuangxiangcidian.ifo

运行应用时出现如下的错误：
liuxg@liuxg:~/snappy/apps$ yd -s "/home/liuxg/.dict_youdao/stardict"
stardict 路径设置成功： /home/liuxg/.dict_youdao/stardict
liuxg@liuxg:~/snappy/apps$ yd dictionary
Traceback (most recent call last):
  File "/usr/local/bin/yd", line 9, in <module>
    load_entry_point('youdao==0.3.1', 'console_scripts', 'yd')()
  File "/usr/local/lib/python2.7/dist-packages/youdao/main.py", line 213, in main
    query(keyword, use_db, use_api, play_voice, use_dict)
  File "/usr/local/lib/python2.7/dist-packages/youdao/main.py", line 83, in query
    dic_file = os.listdir(os.path.join(stardict_base, dic_dir))[0]
OSError: [Errno 20] Not a directory: '/home/liuxg/.dict_youdao/stardict/21shijishuangxiangcidian.dict'

请问这是什么错误！
谢谢！

**Comment by liu-xiao-guo** [comment]
对不起，问题已经解决了。需要一个目录在那里。
